export const PROFESSIONAL_NAVIGATOR_ROUTES = {
  SWIPE: 'SWIPE',
  PROFILE: 'PROFILE',
  // CREATE_JOB_OFFERS  :  'CREATE_JOB_OFFERS',
  CHAT_ROOMS: 'CHAT_ROOMS',
  FAVORITES: 'FAVORITES',
  // JOB_POSTING_DETAIL = 'JOB_POSTING_DETAIL',
};

export default PROFESSIONAL_NAVIGATOR_ROUTES;
